package a_basics_Of_Java;

public class ae_MathFunction {

	public static void main(String[] args) {
		
//		Java Math class has many methods to verious mathematical tasks, some of them are as below
//		- Math.max(x, y)  To find the maximum number among those inside parenthesis
//		- Math.min(x, y)  To find the minimum number among those inside parenthesis
//		- Math.sqrt(x)    To find the squar root of the number inside parenthesis
//		- Math.abs(x)     To find the absolute (positive number) of the number inside parenthesis
//		- Math.random()   To generate/print some numbers randomly
//		- Math.round(x)   to eliminate the decimal parts of float/double

		int a=2, b=4;
		float c=-6.85f;
		
		System.out.println("1. the max number among the given one is: "+ Math.max(a, b));
		System.out.println("2. the minimum number among the given is: " + Math.min(a, b));
		System.out.println("3. the squar root of given mumber 'a' is: " + Math.sqrt(a) +" and b  is " + Math.sqrt(b));
		System.out.println("4. the absolute value of given number b is: " + Math.abs(c));
		System.out.println("5. this is a random number generated by java: " + Math.random());
		System.out.println("6. once decimal part is removed from c, it will be: " + Math.round(c));
		System.out.println("7. lets print c as an absolute and without decimal part: " + Math.abs(Math.round(c)));

			
		
	
		
	}

}
